name: hello-world
description: Hello world action
inputs:
  name:
    description: your name
    required: true
    default: world
outputs:
  date:
    description: "the date"
    value: ${{ steps.hello.outputs.date }}
runs:
  using: "composite"
  steps:
    - id: hello
      shell: bash
      run: |
        echo "hello ${{ inputs.name }}"
        echo "date=$(date)" >> "${GITHUB_OUTPUT}"
    - run: echo ${{ toJson(github)}}
      shell: bash
