name: artifact
on: push
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world" > hello.txt
      - uses: actions/upload-artifact@v4
        with:
          name: hello
          path: hello.txt
          retention-days: 1
  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: hello
          path: hello.txt
      - run: cat hello.txt
