name: command
on: push
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: notice
        run: echo "::notice this is notice::"
      - name: warning
        run: echo "::warning this is warning::"
      - name: error
        run: echo "::error this is error::"
      - name: sample
        run: echo ::notice file={name},line={line},endLine={endLine},title={title}::{message}
      - name: trace
        run: |
          set -x
          date
          hostname
      - name: group
        run: |
          echo "::group::group"
          echo "hello"
          echo "::endgroup::"
      - name: mask
        run: echo "::add-mask::hello"
      - name: showmask
        run: echo "hello"
