name: hello-world
on:
  workflow_dispatch:
    inputs:
      name:
        description: your name
        required: true
        default: world
env:
  name: ${{ github.event.inputs.name }}
defaults:
  run:
    shell: bash
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: hello
        name: action
        uses: ./.github/actions/hello-world/
        with:
          name: ${{ github.event.inputs.name }}
      - run: echo "end"
      - name: date
        env:
          hello: ${{ steps.hello.outputs.date }}
        run: echo "${hello}"
