name: testmkdie
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Test It
        run: go test go/excellent/*.go
